apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: httpd:alpine3.18
        name: httpd
        command: ["/bin/bash", "-c"] #overrride the default command
        args: ["sleep 5; exit 1"] #Sleep for 30 secs then exit with error. 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
