apiVersion: v1
kind: Pod
metadata:
  labels:
  name: nginx-storage
spec:
  containers:
    - image: busybox
      name: busybox
      command: ["/bin/sh", "-c"] 
      args: ["sleep 1000"] 
      volumeMounts:
        - mountPath: /scratch
          name: scratch-volume
    - image: nginx
      name: nginx
      volumeMounts:
        - mountPath: /scratch
          name: scratch-volume
  volumes:
    - name: scratch-volume
      persistentVolumeClaim:
        claimName: mealie-data      
