replicaCount: 2
image:
  # -- Image repository
  repository: ghcr.io/ajnart/homarr
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion
  tag: "0.15.2"
ingress:
  hosts:
    - host: localhost
      paths:
        - path: /
